from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

# Vector Database Schemas (MongoDB)

class DocumentChunk(BaseModel):
    """
    Schema for a document chunk stored in MongoDB Atlas.
    Each chunk represents a segment of the original document, along with its embedding vector.
    """
    chunk_id: str = Field(..., description="Unique identifier for the document chunk")
    text_content: str = Field(..., description="The actual text extracted from the chunk")
    source_file: str = Field(..., description = "The name of the source PDF")
    page_number: Optional[int] = Field(None, description="The page number from which the chunk was extracted")
    
    # NEW METADATA FOR RL AGENT
    primary_concept: str = Field(..., description = "The main educational topic (e.g., 'Recursion')")
    difficulty_level: str = Field(..., description = "Categorized as 'Beginner', 'Intermediate', or 'Advanced'")
    
    embedding: Optional[list[float]] = Field(None, description = "The mathematical vector representation generated by Gemini")
    

# Knowledge Graph Schemas (Neo4j)
class ConceptNode(BaseModel):
    """_summary_
    Represents a single concept node in the Knowledge Graph (e.g., 'Recursion', 'Binary Tree').
    Args:
        BaseModel (_type_): _description_
    """
    
    name: str = Field(..., description = "The name of thee source concept ")
    concept_type: str = Field(..., description= "The category of the concept (e.g., 'Data Structure', 'Algorithm', 'Programming Paradigm')")
    description: Optional[str] = Field(None, description="A brief description of the concept")
    
class ConceptRelationship(BaseModel):
    """
    Represents the edge relationship between two concept nodes in the 
    Knowledge Graph (e.g., 'Recursion' -> 'is_a' -> 'Programming Paradigm').
    
    """
    
    source: str = Field(..., description= "The name of the source concept node")
    target: str = Field(..., description= "The name of the target concept node")
    relation_type: str  = Field(..., description= "How they are related (e.g., 'IS_A', 'REQUIRES', 'PART_OF')")
    description: Optional[str] = Field(None, description= "Optional explanation of how they relate ")
    
    
class ExtractedKnowledge(BaseModel):
    """_summary_
    The master schema that Gemini will output when reading a textbook

    Args:
        BaseModel (_type_): _description_
    """
    nodes: List[ConceptNode]
    relationships: List[ConceptRelationship]
    
    
# Chat and Orchestration Schemas
class ChatQuery(BaseModel):
    """_summary_
    The paylord receives from the Virtual TA frontend when a student asks a question. 
    Args:
        BaseModel (_type_): _description_
    """
    query: str
    student_id: str = Field("student_001", description= "Idetifies for Knowledge tracing")
    session_id: Optional[str] = None
    
class ChatResponse(BaseModel):
    """_summary_
    The response payload sent back to the Virtual TA frontend after processing a student's query. 
    Args:
        BaseModel (_type_): _description_
    """
    answer: str
    retrieved_concepts: List[str] = Field(default_factory=list, description= "Concepts pulled from Neo4j")
    source_documents: List[str] = Field(default_factory=list, description= "PDFs referenced from MongoDB")
    

# Reinforcement Learning (HITL) Schemas
class StudentFeedBack(BaseModel):
    """_summary_
    Captures the Human-in-the-loop reinforcement learning feedback provided by students after interacting 
    with the Virtual TA. 
    This feedback will be used to fine-tune the Gemini model and improve future responses. 
    Args:
        BaseModel (_type_): _description_
    """
    interaction_id: str = Field(..., description= "The unique ID of the specific AI response being rated")
    session_id: str
    student_id: str
    feedback_tag: str = Field(..., description= "Categorized as 'upvote', 'downvote', 'comment', 'Incorrect, 'Too vague', 'Helpful', etc.")
    additional_comment: Optional[str] = Field(None, description= "Additional context provided by the student for their feedback")
    
    